<a href="https://colab.research.google.com/github/markasif/Last_Word_Prediction_using_LSTM_And_GRU/blob/main/Last_Word_Prediction_Using_LSTM_and_GRU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
!pip install nltk
import nltk
nltk.download("gutenberg")
from nltk.corpus import gutenberg
import pandas as pd
data=gutenberg.raw('shakespeare-hamlet.txt')
with open("hamlet.txt","w") as file:
  file.write(data)


[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [19]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

In [20]:
with open("hamlet.txt","r") as file:
  text=file.read().lower()

In [21]:
tokenzier = Tokenizer()
tokenzier.fit_on_texts([text])
total_words =len(tokenzier.word_index)+1
total_words

4818

In [22]:
inputsequence=[]
for line in text.split('\n'):
  token_list = tokenzier.texts_to_sequences([line])[0]
  for i in range(1,len(token_list)):
    n_gram_sequence = token_list[:i+1]
    inputsequence.append(n_gram_sequence)

In [23]:
inputsequence

[[1, 687],
 [1, 687, 4],
 [1, 687, 4, 45],
 [1, 687, 4, 45, 41],
 [1, 687, 4, 45, 41, 1886],
 [1, 687, 4, 45, 41, 1886, 1887],
 [1, 687, 4, 45, 41, 1886, 1887, 1888],
 [1180, 1889],
 [1180, 1889, 1890],
 [1180, 1889, 1890, 1891],
 [57, 407],
 [57, 407, 2],
 [57, 407, 2, 1181],
 [57, 407, 2, 1181, 177],
 [57, 407, 2, 1181, 177, 1892],
 [407, 1182],
 [407, 1182, 63],
 [408, 162],
 [408, 162, 377],
 [408, 162, 377, 21],
 [408, 162, 377, 21, 247],
 [408, 162, 377, 21, 247, 882],
 [18, 66],
 [451, 224],
 [451, 224, 248],
 [451, 224, 248, 1],
 [451, 224, 248, 1, 30],
 [408, 407],
 [451, 25],
 [408, 6],
 [408, 6, 43],
 [408, 6, 43, 62],
 [408, 6, 43, 62, 1893],
 [408, 6, 43, 62, 1893, 96],
 [408, 6, 43, 62, 1893, 96, 18],
 [408, 6, 43, 62, 1893, 96, 18, 566],
 [451, 71],
 [451, 71, 51],
 [451, 71, 51, 1894],
 [451, 71, 51, 1894, 567],
 [451, 71, 51, 1894, 567, 378],
 [451, 71, 51, 1894, 567, 378, 80],
 [451, 71, 51, 1894, 567, 378, 80, 3],
 [451, 71, 51, 1894, 567, 378, 80, 3, 273],
 [451, 71

In [24]:
max_sequence = max((len(x) for x in inputsequence ))
max_sequence

14

In [25]:
input_sequences = np.array(pad_sequences(inputsequence,maxlen=max_sequence,padding="pre"))
input_sequences

array([[   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       [   0,    0,    0, ...,  687,    4,   45],
       ...,
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4],
       [   0,    0,    0, ..., 1047,    4,  193]], dtype=int32)

In [26]:
X=input_sequences[:,:-1]
y=input_sequences[:,-1]

In [27]:
X

array([[   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       ...,
       [   0,    0,    0, ...,  687,    4,   45],
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4]], dtype=int32)

In [28]:
y

array([ 687,    4,   45, ..., 1047,    4,  193], dtype=int32)

In [29]:
import tensorflow as tf

In [30]:
y=tf.keras.utils.to_categorical(y,num_classes=total_words)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [31]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [32]:
 from tensorflow.keras.models import Sequential
 from tensorflow.keras.layers import Dense,Dropout,Embedding,LSTM
 model=Sequential()
 model.add(Embedding(total_words,100,input_length=max_sequence-1))
 model.add(LSTM(150,return_sequences=True))
 model.add(Dropout(0.2))
 model.add(LSTM(100))
 model.add(Dense(total_words,activation="softmax"))
 model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=['accuracy'])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [33]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_2 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ ?                           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_3 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [34]:
history = model.fit(X_train,y_train,epochs=50,batch_size=64,validation_data=(X_test,y_test))

Epoch 1/50
322/322 ━━━━━━━━━━━━━━━━━━━━ 17s 14ms/step - accuracy: 0.0264 - loss: 7.2587 - val_accuracy: 0.0332 - val_loss: 6.7640
Epoch 2/50
322/322 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.0355 - loss: 6.4930 - val_accuracy: 0.0332 - val_loss: 6.8721
Epoch 3/50
322/322 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.0378 - loss: 6.3588 - val_accuracy: 0.0460 - val_loss: 6.8824
Epoch 4/50
322/322 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.0510 - loss: 6.2448 - val_accuracy: 0.0468 - val_loss: 6.8810
Epoch 5/50
322/322 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.0494 - loss: 6.1407 - val_accuracy: 0.0492 - val_loss: 6.9146
Epoch 6/50
322/322 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.0562 - loss: 6.0285 - val_accuracy: 0.0499 - val_loss: 6.9388
Epoch 7/50
322/322 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.0579 - loss: 5.9288 - val_accuracy: 0.0540 - val_loss: 6.9315
Epoch 8/50
322/322 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.0604 - loss: 5.8534 - val_accurac

In [43]:
def predict_next_word(model,tokenzier,text,max_sequence):
  token_list =tokenzier.texts_to_sequences([input_text])[0]
  if len(token_list) >= max_sequence:
    token_list = token_list[-(max_sequence-1):]
  token_list = pad_sequences([token_list],maxlen=max_sequence-1,padding='pre')
  predicted = model.predict(token_list,verbose=0)
  predicted_word_index=np.argmax(predicted,axis=1)
  for word,index in tokenzier.word_index.items():
    if index == predicted_word_index:
      return word
  return None

In [45]:
input_text="to be or not to be"
print(f"input text: {input_text}")
max_sequence=model.input_shape[1]+1
predicted_word=predict_next_word(model,tokenzier,input_text,max_sequence)
print(f"predicted word: {predicted_word}")

input text: to be or not to be
predicted word: all


In [53]:
input_text= "where i had "
print(f"input text: {input_text}")
max_sequence=model.input_shape[1]+1
predicted_word=predict_next_word(model,tokenzier,input_text,max_sequence)
print(f"predicted word: {predicted_word}")

input text: where i had 
predicted word: met


In [54]:
 from tensorflow.keras.layers import GRU
 model=Sequential()
 model.add(Embedding(total_words,100,input_length=max_sequence-1))
 model.add(GRU(150,return_sequences=True))
 model.add(Dropout(0.2))
 model.add(GRU(100))
 model.add(Dense(total_words,activation="softmax"))
 model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=['accuracy'])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [55]:
history = model.fit(X_train,y_train,epochs=50,batch_size=64,validation_data=(X_test,y_test))

Epoch 1/50
322/322 ━━━━━━━━━━━━━━━━━━━━ 7s 13ms/step - accuracy: 0.0282 - loss: 7.2531 - val_accuracy: 0.0332 - val_loss: 6.9354
Epoch 2/50
322/322 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.0354 - loss: 6.6295 - val_accuracy: 0.0412 - val_loss: 6.8501
Epoch 3/50
322/322 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.0448 - loss: 6.3723 - val_accuracy: 0.0511 - val_loss: 6.8158
Epoch 4/50
322/322 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.0551 - loss: 6.1628 - val_accuracy: 0.0641 - val_loss: 6.7403
Epoch 5/50
322/322 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.0751 - loss: 5.8569 - val_accuracy: 0.0703 - val_loss: 6.7868
Epoch 6/50
322/322 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.0836 - loss: 5.6292 - val_accuracy: 0.0709 - val_loss: 6.8183
Epoch 7/50
322/322 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.0953 - loss: 5.3910 - val_accuracy: 0.0705 - val_loss: 6.9421
Epoch 8/50
322/322 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.1079 - loss: 5.1501 - val_accurac

In [56]:
input_text= "where i had "
print(f"input text: {input_text}")
max_sequence=model.input_shape[1]+1
predicted_word=predict_next_word(model,tokenzier,input_text,max_sequence)
print(f"predicted word: {predicted_word}")

input text: where i had 
predicted word: met
